on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    services:
      db:
        image: stripemock/stripe-mock:v0.73.1
        ports: ['12123:12111']
    strategy:
      matrix:
        otp: [21.x, 22.x]
        elixir: [1.7.x, 1.8.x, 1.9.x]
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Check formatting
        if: matrix.elixir == '1.9.x'
        run: mix format --check-formatted
      - name: Install Dependencies
        run: mix deps.get
      - name: Compile project
        run: mix compile --warnings-as-errors
      - name: Run tests
        run: mix test  --cover